version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - "./:/usr/src/app:delegated"
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
